#!/bin/bash
set -e

usage() { echo "Usage: $(basename $0) [-d] [-f] {init|list|rdumpfs|ldumpfs} {daily|weekly|monthly}"; exit 1; }

bindrootfs() { src=$HOME/rootfs && mkdir -p $src && mount -obind / $src; }
unbindrootfs() { umount $src && rmdir $src; }

[[ $# -eq 0 || "$1" = "-h" || "$1" = "--help" || "$1" = "help" ]] && usage
[[ "$1" = "-d" ]] && DRYRUN="echo" && shift

declare -A SRCS
[[ -f /etc/rdumpfs-rota.conf ]] && source /etc/rdumpfs-rota.conf

[[ "$1" = "-f" ]] && OPTS="-f $OPTS" && shift

cmd=$1 && shift

[[ $# -gt 0 && ${SRCS[$1]+exists} ]] && sources=${SRCS[$1]} || sources="$*"

for src in $sources ; do
    destdir=$(echo $src|sed -e 's:/::;s:/:_:g')

    case "$cmd" in
	init)
	    [[ -n "$REMOTESERVER" ]] && $DRYRUN ssh $REMOTESERVER mkdir -p $REMOTEDEST/$destdir
	    [[ -n "$LOCALDEST" ]] && $DRYRUN mkdir -p $LOCALDEST/$destdir
	    ;;
	list)
	    [[ -n "$REMOTESERVER" ]] && $DRYRUN rsync ${REMOTESERVER}:${REMOTEDEST}/$destdir
	    [[ -n "$LOCALDEST" ]] && $DRYRUN ls ${LOCALDEST}/$destdir
	    ;;
	*dumpfs)
	    [[ "$src" = "rootfs" ]] && bindrootfs
	    [[ "$cmd" = "rdumpfs" ]] && $DRYRUN rdumpfs $OPTS $src ${REMOTESERVER}:${REMOTEDEST}/$destdir >>$LOGFILE 2>&1
	    [[ "$cmd" = "ldumpfs" ]] && $DRYRUN rdumpfs $OPTS $src ${LOCALDEST}/$destdir >>$LOGFILE 2>&1
	    [[ "$src" = "$HOME/rootfs" ]] && unbindrootfs
	    ;;
	*)
	    usage
	    ;;
    esac
    
done 

exit 0
